receivers:  
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # logzio:
  #   account_token: 7f73edf7-5812-42a1-b46a-ae3e45730fb4
  #   #region: "<<LOGZIO_ACCOUNT_REGION_CODE>>" - (Optional)
  #   region: us
  logging:
    loglevel: debug
  file:
    path: /home/neoito/projects/Accounting/appblox-deployments/open-telemetry/logs.json
  jaeger: 
    endpoint: localhost:14250
    tls:
      insecure: true

processors:
  batch:

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,file,jaeger]